export const SCREEN_SET_MESSAGE = 'SCREEN_SET_MESSAGE';
export const SCREEN_ACTIVE = 'SCREEN_ACTIVE';
export const SCREEN_IDLE = 'SCREEN_IDLE';
export const DEVICE_LOCK = 'DEVICE_LOCK';
export const SET_PASSCODE = 'SET_PASSCODE';
export const SAVE_PASSCODE = 'SAVE_PASSCODE';
export const READ_SCREEN_MESSAGE = 'READ_SCREEN_MESSAGE';
